---
- ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}"
        - main.yml
      paths:
        - 'vars'

- ansible.builtin.include_tasks: setup-CentOS-7.yml
  when: ansible_distribution == "CentOS"

- ansible.builtin.include_tasks: setup-Debian-20.yml
  when: ansible_distribution == "Ubuntu"

- name: check out main branch
  git:
    repo: 'https://github.com/monicahq/monica'
    dest: /srv/monicahq
    version: main

- name: Add the user
  user:
    name: monicahq
    shell: /usr/bin/nologin
    home: /srv/monicahq

- name: install composer
  include_role:
    name: geerlingguy.composer

- name: install composer dependencies
  composer:
    command: install
    working_dir: /srv/monicahq
  environment:
    COMPOSER_NO_INTERACTION: "1"
    COMPOSER_ALLOW_SUPERUSER: "1"
    
- name: prepare configuration
  template:
    src: env.j2
    dest: /srv/monicahq/.env

- name: Run an initial key generation
  command: "/usr/bin/php /srv/monicahq/artisan key:generate"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Run an initial migration
  command: "/usr/bin/php /srv/monicahq/artisan monica:setup --force"
  args:
    chdir: /srv/monicahq/
  tags: molecule-notest

- name: Place a scheduler cron job
  cron:
    user: monicahq
    name: "scheduler"
    job: "/usr/bin/php /srv/monicahq/artisan schedule:run"

- name: Recursively change ownership of a directory
  file:
    path: /srv/monicahq
    state: directory
    recurse: yes
    owner: monicahq
    group: "{{ group_name }}"

- name: Put right permissions to storage
  file:
    path: /srv/monicahq/storage
    state: directory
    recurse: yes
    mode: g+w

- name: Create nginx vhost config
  template:
    src: monicahq.conf.j2
    dest: "{{ nginx_conf }}"

- name: Remove default nginx configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: ansible_distribution  == "Ubuntu"

- name: Install packages based on package json.
  community.general.npm:
    path: /srv/monicahq

- name: Build npm
  shell: npm run build
  args:
    chdir: /srv/monicahq

- name: reload service php-fcgi
  become: true
  service:
    name: "{{ service_fpm }}"
    state: reloaded
    use: "a turnip"

- name: reload service nginx
  become: true
  service:
    name: nginx
    state: reloaded
    use: "a turnip"