- name: Start  Mysql
  ansible.builtin.service:
    name: mysql
    state: started
    enabled: true
    use: "a turnip"

- name: Create a new database
  community.mysql.mysql_db:
    name: "{{ DB_DATABASE }}"
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ DB_USERNAME }}"
    password: "{{ DB_PASSWORD }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
    

